name: Run Python script every 5 minutes

on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        CAR_ALERT_BOT_TOKEN: ${{ secrets.CAR_ALERT_BOT_TOKEN }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
    steps:
    - name: Set  Environment Variables
      run: |
        export MY_VAR=TESTTESTTEST
    - name: Step 1
      run: echo MY_VAR
    - name: Step 2
      run: echo ${{ secrets.CAR_ALERT_BOT_TOKEN }}

