name: Run Python script every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the secret and decode it to a file
      env:
        CERTIFICATE_BASE64: ${{ secrets.CAR_ALERT_BOT_TOKEN }}
      run: |
        echo $CERTIFICATE_BASE64

