name: Run Python script every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        CAR_ALERT_BOT_TOKEN: 6720148798:AAGtKhsMhyyro-ZAlLOlAe6f-7PpN5tMVAU
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # замените '3.x' на версию Python, которую вы используете
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python script
      run: python main.py # замените 'your_script.py' на имя вашего скрипта
