name: Run Python script every 30 minutes

on:
  push:
    branches:
      - main
  schedule:
    # - cron: '0 10,18 * * *'

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      POSTGRESQL_DB_PASSWORD: ${{ secrets.POSTGRESQL_DB_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome & Chromedriver
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable
        sudo apt install -y chromium-chromedriver
        echo "Chrome version:"
        google-chrome --version
        echo "Chromedriver version:"
        chromedriver --version

    - name: Run Selenium script
      run: python main.py

